import StoreProvider from "./StoreProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className='overflow-y-hidden'>{children}</body>
      </html>
    </StoreProvider>
  );
}
